version: 0.2 
phases:
  install:
    runtime-versions:
      java: jdk-8
  pre_build:
    commands:
      - cd src/main/resources/static
      - npm install bower -g
      - bower install --allow-root
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/devops-0.0.1-SNAPSHOT.jar
    - scripts/update_crontab.sh
    - scripts/httpd_service.sh
    - scripts/regservice.sh
    - webconfig/oidc.conf
    - webconfig/vhost.conf
  
